version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    commit-message:
      # Prefixes are chosen to influence release-notes sections (conventional commits preset)
      prefix: "fix"
      # Development dependency updates should be classified as non-user-facing changes
      prefix-development: "chore"
      include: "scope"

  - package-ecosystem: "pip"
    directory: "/.github/workflows" # CI pinned dependency manifests
    schedule:
      interval: "weekly"
    commit-message:
      # CI tooling updates should be classified as non-user-facing changes
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    commit-message:
      # Les actions GitHub ne vont pas dans le changelog
      prefix: "chore"
      include: "scope"
