version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    commit-message:
      # requirements.txt -> Apparaîtra dans le changelog sous "Bug Fixes"
      prefix: "fix" 
      # requirements-dev.txt -> Sera ignoré par le changelog
      prefix-development: "chore"
      include: "scope"

  - package-ecosystem: "pip"
    directory: "/.github/workflows" # CI pinned dependency manifests
    schedule:
      interval: "weekly"
    commit-message:
      # L'outillage CI ne va pas dans le changelog
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    commit-message:
      # Les actions GitHub ne vont pas dans le changelog
      prefix: "chore"
      include: "scope"
