"""Workout table package — re-exports all public symbols."""

from ui.workout_table.render import (
    render_distance_range_selector,
    render_duration_range_selector,
    render_workout_table,
)
from ui.workout_table.rows import (
    _MISSING_SORT,
    _TABLE_ROW_FIELDS,
    _annotate_route_with_heart_rate,
    _apply_activity_specific_fields,
    _apply_range_filters,
    _build_field_pair,
    _build_table_rows,
    _build_workout_rows,
    _enrich_routes_with_heart_rate,
    _extract_cycling_fields,
    _extract_date_field,
    _extract_distance_field,
    _extract_elevation_field,
    _extract_hiking_fields,
    _extract_row_data,
    _extract_running_fields,
    _extract_swimming_fields,
    _extract_walking_fields,
    _extract_workout_heart_rate_samples,
    _find_row_index,
    _format_pace,
    _is_missing_route_placeholder,
    _log_malformed_route_fragment,
    _nearest_vo2_max,
    _normalize_datetime,
    _safe_float,
)

__all__ = [
    "render_workout_table",
    "render_distance_range_selector",
    "render_duration_range_selector",
    "_MISSING_SORT",
    "_TABLE_ROW_FIELDS",
    "_annotate_route_with_heart_rate",
    "_apply_activity_specific_fields",
    "_apply_range_filters",
    "_build_field_pair",
    "_build_table_rows",
    "_build_workout_rows",
    "_enrich_routes_with_heart_rate",
    "_extract_cycling_fields",
    "_extract_date_field",
    "_extract_distance_field",
    "_extract_elevation_field",
    "_extract_hiking_fields",
    "_extract_row_data",
    "_extract_running_fields",
    "_extract_swimming_fields",
    "_extract_walking_fields",
    "_extract_workout_heart_rate_samples",
    "_find_row_index",
    "_format_pace",
    "_is_missing_route_placeholder",
    "_log_malformed_route_fragment",
    "_nearest_vo2_max",
    "_normalize_datetime",
    "_safe_float",
]
